Kitakun.VkModules.Web/Areas/UltraAdmin/Models/HomeViewModel.cs
using Kitakun.VkModules.Core.Domain;

namespace Kitakun.VkModules.Web.Areas.UltraAdmin.Models
{
	public class HomeViewModel
	{
		/// <summary>
		/// Filter query (long)
		/// </summary>
		public string SearchString { get; set; }
		/// <summary>
		/// Founded by filter or initial entities
		/// </summary>
		public Subscription[] Subscriptions { get; set; }

		public string ExceptionMessage { get; set; }
		public string WarningMessage { get; set; }
	}
}

Kitakun.VkModules.Web/Areas/UltraAdmin/Controllers/GroupSettingsController.cs
namespace Kitakun.VkModules.Web.Areas.UltraAdmin.Controllers
{
    using System;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Cors;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.EntityFrameworkCore;

    using Kitakun.VkModules.Web.Infrastructure;
    using Kitakun.VkModules.Persistance;
    using Kitakun.VkModules.Core.Domain;
    using System.Linq;

    [AllowAnonymous]
    [Area(AreaNames.UltraAdminAreaName)]
    [EnableCors(WebConstants.AllCorsName)]
    public class GroupSettingsController : Controller
    {
        private readonly IVkDbContext _dbContext;

        public GroupSettingsController(IVkDbContext dbContext)
        {
            _dbContext = dbContext ?? throw new ArgumentNullException(nameof(dbContext));
        }

        [HttpGet]
        public IActionResult Create() => View("Index", new GroupSettings());

        [HttpGet]
        public async Task<IActionResult> Index([FromQuery] long? groupId)
        {
            var expectedEntity = await _dbContext.GroupSettings.FirstOrDefaultAsync(w => w.GroupId == groupId.Value);
            if (expectedEntity == null)
                return NotFound();

            return View("Index", expectedEntity);
        }

        [HttpGet]
        public async Task<IActionResult> List()
        {
            var expectedEntity = await _dbContext.GroupSettings.Take(25).ToArrayAsync();

            return View("List", expectedEntity);
        }

        [HttpPost]
        public async Task<IActionResult> Create([FromForm] GroupSettings model)
        {
            await _dbContext.GroupSettings.AddAsync(model);

            await _dbContext.SaveChangesAsync();

            ViewBag.Message = "Успешно создано";

            return View("Index", model);
        }

        [HttpPost]
        public async Task<IActionResult> Index([FromForm] GroupSettings model)
        {
            var existingEntity = await _dbContext.GroupSettings.FindAsync(model.Id);
            if (existingEntity == null)
                return NotFound();

            existingEntity.ReverseGroup = model.ReverseGroup;
            existingEntity.GroupAppToken = model.GroupAppToken;
            existingEntity.TopLikersHeaderMessage = model.TopLikersHeaderMessage;

            existingEntity.LikePrice = model.LikePrice;
            existingEntity.CommentPrice = model.CommentPrice;
            existingEntity.RepostPrice = model.RepostPrice;

            await _dbContext.SaveChangesAsync();

            ViewBag.Message = "Успешно обнавлено";

            return View("Index", existingEntity);
        }

        [HttpPost]
        public async Task<IActionResult> Delete([FromForm] GroupSettings model)
        {
            var existingEntity = await _dbContext.GroupSettings.FindAsync(model.Id);
            if (existingEntity == null)
                return NotFound();

            _dbContext.GroupSettings.Remove(existingEntity);

            await _dbContext.SaveChangesAsync();

            ViewBag.Message = "Успешно удалено";

            existingEntity.Id = -1;
            return View("Index", existingEntity);
        }
    }
}

Kitakun.VkModules.Web/Areas/UltraAdmin/Controllers/HomeController.cs
namespace Kitakun.VkModules.Web.Areas.UltraAdmin.Controllers
{
    using System;
    using System.Linq;
    using System.Threading.Tasks;

    using Hangfire;
    using Microsoft.AspNetCore.Cors;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.EntityFrameworkCore;

    using Kitakun.VkModules.Web.Infrastructure;
    using Kitakun.VkModules.Services.Abstractions;
    using Kitakun.VkModules.Web.Areas.UltraAdmin.Models;
    using Kitakun.VkModules.Persistance;
    using Kitakun.VkModules.Web.Controllers;

    [AllowAnonymous]
    [Area(AreaNames.UltraAdminAreaName)]
    [EnableCors(WebConstants.AllCorsName)]
    public class HomeController : Controller
    {
        const int takeOnly = 5;

        private readonly IWebContext _webContext;
        private readonly VkDbContext _dbContext;
        private readonly BackgroundUpdater _bgUpdater = default;

        public HomeController(
            IWebContext webContext,
            VkDbContext dbContext)
        {
            _webContext = webContext ?? throw new ArgumentNullException(nameof(webContext));
            _dbContext = dbContext ?? throw new ArgumentNullException(nameof(dbContext));
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
#if RELEASE
            if (!_webContext.IsUltraAdmin)
            {
                return NotFound();
            }
#endif

            var model = new HomeViewModel
            {
                SearchString = string.Empty
            };
            try
            {
                model.Subscriptions = await _dbContext
                    .Subscriptions
                    .AsNoTracking()
                    .OrderBy(x => x.From)
                    .Take(takeOnly)
                    .ToArrayAsync();

                model.WarningMessage = $"Показано {takeOnly} элементов по дате начала";
            }
            catch (Exception es)
            {
                model.ExceptionMessage = es.Message;
            }

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SearchSubs([FromForm] string searchString)
        {
            var model = new HomeViewModel
            {
                SearchString = searchString
            };

            try
            {
                if (!string.IsNullOrEmpty(searchString))
                {
                    model.Subscriptions = await _dbContext
                        .Subscriptions
                        .AsNoTracking()
                        .Where(w => searchString.Contains(w.UserId.ToString()) || searchString.Contains(w.GroupId.ToString()))
                        .ToArrayAsync();
                }
                else
                {
                    const int takeOnly = 5;

                    model.Subscriptions = await _dbContext
                        .Subscriptions
                        .AsNoTracking()
                        .OrderBy(x => x.From)
                        .Take(takeOnly)
                        .ToArrayAsync();

                    model.WarningMessage = $"Показано {takeOnly} элементов по дате начала";
                }
            }
            catch (Exception es)
            {
                model.ExceptionMessage = es.Message;
            }

            return View(nameof(Index), model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> SearchGroupSetting([FromForm] string searchGroupSettings)
        {
            if (long.TryParse(searchGroupSettings, out var parsedGroupId))
            {
                var hasSetts = await _dbContext.GroupSettings.AnyAsync(a => a.GroupId == parsedGroupId);
                if (hasSetts)
                {
                    return RedirectToAction(
                        nameof(GroupSettingsController.Index),
                        nameof(GroupSettingsController).Replace("Controller", ""),
                        new
                        {
                            groupId = parsedGroupId
                        });
                }
                else
                {
                    return RedirectToAction(
                        nameof(GroupSettingsController.Create),
                        nameof(GroupSettingsController).Replace("Controller", ""));
                }
            }
            else
            {
                var model = new HomeViewModel
                {
                    SearchString = string.Empty,
                    WarningMessage = $"Can't parse group Id for '{searchGroupSettings}'",
                    Subscriptions = await _dbContext
                        .Subscriptions
                        .AsNoTracking()
                        .OrderBy(x => x.From)
                        .Take(takeOnly)
                        .ToArrayAsync()
                };
                return View(nameof(Index), model);
            }
        }

        [HttpPost]
        public Task UpdateDatabase() => _dbContext.Database.MigrateAsync();

        public async Task<IActionResult> RunBackgroundUpdate()
        {
            var groupIdsWithToken = await _dbContext
                .GroupSettings
                .Where(w => w.GroupAppToken.Length > 0 && w.GroupId.HasValue)
                .Select(s => s.GroupId.Value)
                .ToArrayAsync();

            for (var i = 0; i < groupIdsWithToken.Length; i++)
            {
                const string every15minterCron = "*/15 * * * *";
                RecurringJob.AddOrUpdate(() => _bgUpdater.Run(groupIdsWithToken[i], null), every15minterCron);
            }

            return Ok("done");
        }
    }
}

Kitakun.VkModules.Web/Areas/UltraAdmin/Controllers/SubscriptionsController.cs
namespace Kitakun.VkModules.Web.Areas.UltraAdmin.Controllers
{
	using System;
	using System.Threading.Tasks;

	using Microsoft.AspNetCore.Cors;
	using Microsoft.AspNetCore.Mvc;
	using Microsoft.AspNetCore.Authorization;

	using Kitakun.VkModules.Web.Infrastructure;
	using Kitakun.VkModules.Web.Areas.UltraAdmin.Models;
	using Kitakun.VkModules.Persistance;
	using Kitakun.VkModules.Core.Domain;

	[AllowAnonymous]
	[Area(AreaNames.UltraAdminAreaName)]
	[EnableCors(WebConstants.AllCorsName)]
	public class SubscriptionsController : Controller
	{
		private readonly IVkDbContext _dbContext;

		public SubscriptionsController(IVkDbContext dbContext)
		{
			_dbContext = dbContext ?? throw new ArgumentNullException(nameof(dbContext));
		}

		public IActionResult Index() => RedirectToActionPermanent("Index", "Home");

		[HttpGet]
		public IActionResult Create() =>
			View(new CreateSubscriptionModel
			{
				From = DateTime.Now.Date,
				To = DateTime.Now.Date.AddMonths(1)
			});

		[HttpPost]
		public async Task<IActionResult> Create([FromForm] CreateSubscriptionModel model)
		{
			var newSubscription = new Subscription
			{
				From = model.From,
				To = model.To,
				UserId = model.UserId,
				GroupId = model.GroupId
			};
			await _dbContext.Subscriptions.AddAsync(newSubscription);
			await _dbContext.SaveChangesAsync();

            ViewBag.Message = "Успешно создано";

            return View(model);
		}

		[HttpGet]
		public async Task<IActionResult> Edit([FromRoute] int? id)
		{
			var subscription = await _dbContext.Subscriptions.FindAsync(id.Value);

			return View("Create", new CreateSubscriptionModel
			{
				Id = subscription.Id,
				From = subscription.From,
				To = subscription.To,
				GroupId = subscription.GroupId,
				UserId = subscription.UserId
			});
		}

		[HttpPost]
		public async Task<IActionResult> Edit([FromForm] CreateSubscriptionModel model)
		{
			var subscription = await _dbContext.Subscriptions.FindAsync(model.Id);

			subscription.From = model.From;
			subscription.To = model.To;
			subscription.UserId = model.UserId;
			subscription.GroupId = model.GroupId;

			await _dbContext.SaveChangesAsync();

            ViewBag.Message = "Успешно обнавлено";

            return View("Create", model);
		}
	}
}

Kitakun.VkModules.Web/Controllers/HomeController.cs
namespace Kitakun.VkModules.Web.Controllers
{
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Cors;
    using Microsoft.AspNetCore.Mvc;
    using Microsoft.AspNetCore.Authorization;

    using Kitakun.VkModules.Web.Infrastructure;
    using Kitakun.VkModules.Web.WebModels;
    using Kitakun.VkModules.Services.Abstractions;

    [AllowAnonymous]
    [EnableCors(WebConstants.AllCorsName)]
    public class HomeController : Controller
    {
        private readonly IWebContext _webContext;
        private readonly ISubscriptionsService _subService;

        public HomeController(
            IWebContext webContext,
            ISubscriptionsService subService)
        {
            _webContext = webContext ?? throw new System.ArgumentNullException(nameof(webContext));
            _subService = subService ?? throw new System.ArgumentNullException(nameof(subService));
        }

        [HttpGet]
        public IActionResult Index() => View("Welcome");

        [HttpGet("App")]
        public async Task<IActionResult> App()
        {
            var groupId = _webContext.GroupId;

            var hasSub = groupId != 0
                ? await _subService.GroupHasSubscription(groupId)
                : false;

            return View(
                "Index",
                new HomeModel
                {
                    HasSubscription = hasSub,
                    IsAdmin = _webContext.IsUltraAdmin || _webContext.IsAdmin
                }
            );
        }
    }
}

Kitakun.VkModules.Web/Areas/UltraAdmin/Views/Home/Index.cshtml
@model Kitakun.VkModules.Web.Areas.UltraAdmin.Models.HomeViewModel
@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>UltraAdmin</h1>

@if (!string.IsNullOrEmpty(Model.ExceptionMessage) || !string.IsNullOrEmpty(Model.WarningMessage))
{
    <div class="page-block">
        <div class="info-wrap">
            @if (!string.IsNullOrEmpty(Model.WarningMessage))
            {
                <div class="info">
                    @Model.WarningMessage
                </div>
            }
            @if (!string.IsNullOrEmpty(Model.ExceptionMessage))
            {
                <div class="error">
                    @Model.ExceptionMessage
                </div>
            }
        </div>
    </div>
}

<div class="page-block">
    <form asp-controller="Home" asp-area="UltraAdmin" asp-action="SearchGroupSetting">
        @Html.AntiForgeryToken()
        <h3>Search group settings</h3>
        <input type="text" name="searchGroupSettings" class="singleline-input" placeholder="Group ID">
        <button id="btnSearch" type="submit" class="flat-button">Start Search</button>
    </form>
</div>

<div class="page-block">
    <form asp-controller="Home" asp-area="UltraAdmin" asp-action="SearchSubs">
        @Html.AntiForgeryToken()
        <h3>Search subscription</h3>
        <input type="text" name="searchString" class="singleline-input" placeholder="Search" value="@Model.SearchString">
        <button id="btnSearch" type="submit" class="flat-button">Start Search</button>

        @if (Model.Subscriptions != null && Model.Subscriptions.Length > 0)
        {
            <table class="fullwidth">
                <thead>
                    <tr>
                        <th>UserID</th>
                        <th>GroupID</th>
                        <th>From</th>
                        <th>To</th>
                        <th></th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var sub in Model.Subscriptions)
                    {
                        <tr>
                            <td class="center">@sub.UserId</td>
                            <td class="center">@sub.GroupId</td>
                            <td class="center">@sub.From.ToShortDateString()</td>
                            <td class="center">@(sub.To?.ToShortDateString() ?? "-")</td>
                            <td>
                                <a asp-controller="Subscriptions"
                                   asp-action="Edit"
                                   asp-route-id="@sub.Id"
                                   class="flat-button">Edit</a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        }
    </form>
</div>

<div class="page-block">
    <h3>Navigation</h3>

    <a asp-controller="Subscriptions"
       asp-action="Create"
       class="flat-button">Создать подписку</a>

    <a asp-controller="GroupSettings"
       asp-action="Create"
       class="flat-button">Создать настройку для группы</a>

    <form asp-controller="Home" asp-area="UltraAdmin" asp-action="UpdateDatabase">
        <button type="submit" class="flat-button">Migrate database</button>
    </form>

    @*<form asp-controller="Home" asp-area="UltraAdmin" asp-action="RunBackgroundUpdate">
        <button type="submit" class="flat-button">Run background update</button>
    </form>*@
</div>